### ISSUE TITLE
云展网pdf下载

### ISSUE THREAD

**Issue by Sullivangithub** [Kaoruha/YunZhanDownloader#1]
https://greasyfork.org/zh-CN/scripts/483545-%E4%BA%91%E5%B1%95%E7%BD%91pdf%E4%B8%8B%E8%BD%BD-yunzhandownloader

无法安装。
看不到Chrome的扩展，网站也没有出现那个“下载”按钮。
hope this can helps to do upgrade, :)

我想下载这个：
https://bookh.yunzhan365.com/zorbt/ipat/mobile/index.html?hyztg=1

**Comment by Kaoruha** [comment]
在我的记忆里, 我没有发布过啥Chrome组件, 这只是个本地python项目, 你发的这个应该不是一个项目. 你可以试着按照本项目Readme的流程尝试下载,如果遇到问题可以再反馈.
